export const employeeReducerActions = {
  SET_ITEM: "SET_ITEM",
  ADD_ITEM: "ADD_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  ADD_SINGLE_ITEM: "ADD_SINGLE_ITEM",
  REMOVE_SINGLE_ITEM: "ADD_SINGLE_ITEM",
};
